### ISSUE TITLE
Overlays contain transparent / translucent pixels outside the desired area

### ISSUE THREAD

**Issue by toniosj** [thebezelproject/bezelproject-N64#2]
Some overlays contain transparent / translucent pixels outside the desired area.
![example](https://user-images.githubusercontent.com/20826760/74558218-2be46880-4f62-11ea-9172-e64c43c64795.png)

**Comment by thebezelproject** [comment]
If you can identify the ones that need reworked, I can look at them.

**Comment by toniosj** [comment]
Here N64 games. 

Bio F.R.E.A.K.S. (USA)
Blast Corps (USA)
Blues Brothers 2000 (Europe) (En,Fr,De,Es,It,Nl)
Body Harvest (USA)
Bomberman 64 (USA)
Bottom of the 9th (USA)
Brunswick Circuit Pro Bowling (USA)
Buck Bumble (Europe) (En,Fr,De,Es,It)
Bug's Life, A (USA)
Bust-A-Move 2 - Arcade Edition (USA)
California Speed (USA)
Carmageddon 64 (Europe) (En,Fr,De,Es)
Castlevania (USA)
Castlevania - Legacy of Darkness (USA)
Centre Court Tennis (Europe)
Chameleon Twist (USA)
Chameleon Twist 2 (USA)
Charlie Blast's Territory (USA)
Chopper Attack (USA)
Clay Fighter - Sculptor's Cut (USA)
Clay Fighter 63 1-3 (USA)
Command & Conquer (USA)
Conker's Bad Fur Day (USA)
Cruis'n Exotica (USA)
Cruis'n USA (USA)
Cruis'n World (USA)
CyberTiger (USA)
Daffy Duck Starring as Duck Dodgers (Europe) (En,Fr,De,Es,It,Nl)
Dark Rift (USA)
Destruction Derby 64 (USA)
Donald Duck - Goin' Quackers (USA) (En,Fr,De,Es,It)
Donkey Kong 64 (Europe) (En,Fr,De,Es)
Doom 64 (USA)
Dr. Mario 64 (USA)
Dual Heroes (USA)
Duke Nukem - Zero Hour (USA)
Duke Nukem 64 (USA)
Earthworm Jim 3D (Europe) (En,Fr,De,Es,It)
ECW Hardcore Revolution (USA)
Elmo's Letter Adventure (USA)
Elmo's Number Journey (USA)
Excitebike 64 (USA)
Extreme-G (Europe) (En,Fr,De,Es,It)
Extreme-G XG2 (Europe) (En,Fr,De,Es,It)
F1 Racing Championship (Europe) (En,Fr,De,Es,It)
G.A.S.P!! Fighters' NEXTream (Europe)
Iggy's Reckin' Balls (USA)
In-Fisherman - Bass Hunter 64 (USA)
Indiana Jones and the Infernal Machine (USA)
Indy Racing 2000 (USA)
International Superstar Soccer '98 (USA)
International Superstar Soccer 2000 (USA) (En,Es)
International Superstar Soccer 64 (USA)
International Track & Field 2000 (USA)
Jeopardy! (USA)
Jeremy McGrath Supercross 2000 (USA)
Jet Force Gemini (Europe) (En,Fr,De,Es)
John Romero's Daikatana (USA)
Ken Griffey Jr.'s Slugfest (USA)
Killer Instinct Gold (USA)
Kirby 64 - The Crystal Shards (USA)
Knife Edge - Nose Gunner (USA)
Knockout Kings 2000 (USA)
Kobe Bryant in NBA Courtside (Europe)
Legend of Zelda, The - Majora's Mask (Europe) (En,Fr,De,Es)
Legend of Zelda, The - Ocarina of Time (USA)
LEGO Racers (USA) (En,Fr,De,Es,It,Nl,Sv,No,Da,Fi)
Lode Runner 3-D (Europe) (En,Fr,De,Es,It)
Mace - The Dark Age (USA)
Madden Football 64 (USA)
Madden NFL 2000 (USA)
Madden NFL 99 (USA)
Micro Machines 64 Turbo (Europe) (En,Fr,De,Es,It)
Midway's Greatest Arcade Hits - Volume 1 (USA)
Mike Piazza's StrikeZone (USA)
Mischief Makers (USA)
Monaco Grand Prix - Racing Simulation 2 (Europe) (En,Fr,Es,It)
Monopoly (USA)
Monster Truck Madness 64 (Europe) (En,Fr,De,Es,It)
Mortal Kombat 4 (USA)
Mortal Kombat Mythologies - Sub-Zero (USA)
Mortal Kombat Trilogy (USA)
MRC - Multi Racing Championship (USA)
NBA Live 2000 (USA) (En,Fr,De,Es)
NBA Live 99 (USA) (En,Fr,De,Es,It)
New Tetris, The (USA)
NFL Blitz (USA)
NFL Blitz 2001 (USA)
NFL QB Club 2001 (USA)
NFL Quarterback Club 2000 (USA)
NFL Quarterback Club 98 (USA)
NFL Quarterback Club 99 (USA)
NHL 99 (USA)
NHL Breakaway 99 (USA)
NHL Pro 99 (Europe)
Operation WinBack (Europe) (En,Fr,De,Es,It)
S.C.A.R.S. (USA)
San Francisco Rush 2049 (Europe) (En,Fr,De,Es,It,Nl)
Scooby-Doo! - Classic Creep Capers (USA)
Shadow Man (Europe) (En,Es,It)
Shadowgate 64 - Trials of the Four Towers (Europe) (Es,It)
Snowboard Kids (USA)
Snowboard Kids 2 (USA)
South Park (Europe) (En,Fr,Es)
Space Invaders (USA)
SpaceStation Silicon Valley (Europe) (En,Fr,De,Es,It,Nl,Pt)
Supercross 2000 (USA)
Superman (Europe) (En,Fr,De,Es,It,Nl)
Tarzan (USA)
Taz Express (Europe) (En,Fr,De,Es,It,Nl)
Tetrisphere (USA)
Tigger's Honey Hunt (Europe) (En,Fr,De,Es,It,Nl,Da)
Tom and Jerry in Fists of Furry (Europe) (En,Fr,De,Es,It,Nl)
Tom Clancy's Rainbow Six (USA)
Tonic Trouble (Europe) (En,Fr,De,Es,It)
Tony Hawk's Pro Skater (USA)
Tony Hawk's Pro Skater 2 (USA)
Tony Hawk's Pro Skater 3 (USA)
Top Gear Hyper-Bike (USA)
Top Gear Overdrive (USA)
Top Gear Rally (USA)
Top Gear Rally 2 (USA)
Toy Story 2 - Buzz Lightyear to the Rescue! (USA)
Transformers - Beast Wars Transmetals (USA)
Triple Play 2000 (USA)
Turok - Dinosaur Hunter (USA)
Turok - Rage Wars (USA)
Turok 2 - Seeds of Evil (Europe) (En,Fr,Es,It)
Turok 3 - Shadow of Oblivion (USA)
Twisted Edge - Extreme Snowboarding (USA)
V-Rally Edition 99 (USA)
Vigilante 8 (USA)
Vigilante 8 - 2nd Offense (USA)
Virtual Chess 64 (Europe) (En,Fr,De,Es,It,Nl)
Virtual Pool 64 (USA)
Waialae Country Club - True Golf Classics (USA)
War Gods (USA)
Wave Race 64 (USA)
Wayne Gretzky's 3D Hockey '98 (Europe) (En,Fr,De,Es)
Wayne Gretzky's 3D Hockey (Europe) (En,Fr,De,Es)
WCW Backstage Assault (USA)
WCW Mayhem (USA)
WCW Nitro (USA)
WCW vs. nWo - World Tour (USA)
WCW-nWo Revenge (USA)
Wetrix (USA) (En,Fr,De,Es,It,Nl)
Wheel of Fortune (USA)
Wipeout 64 (USA)
World Cup 98 (USA) (En,Fr,De,Es,It,Nl,Sv,Da)
World Driver Championship (Europe) (En,Fr,De,Es,It)
Worms Armageddon (Europe) (En,Fr,De,Es,It,Nl)
WWF Attitude (USA)
WWF No Mercy (USA)
WWF War Zone (USA)
WWF WrestleMania 2000 (USA)
Xena - Warrior Princess - The Talisman of Fate (USA)

**Comment by toniosj** [comment]
Here an example:

![example](https://user-images.githubusercontent.com/20826760/74563105-51766f80-4f6c-11ea-8803-612c79d3657f.png)

**Comment by thebezelproject** [comment]
That you very much for the information. I'll submit the info to make sure the files are cleaned up. I'll post an update here when the new files are available.

**Comment by thebezelproject** [comment]
I have updated the png files listed and updated the Github archive.

**Comment by toniosj** [comment]
Nice!!!

**Comment by toniosj** [comment]
This game has not been fixed: WCW-nWo Revenge (USA).PNG

![WCW-nWo Revenge (USA)](https://user-images.githubusercontent.com/20826760/75185945-462efb00-5747-11ea-94c2-9f0a9a9fc55b.PNG)

**Comment by thebezelproject** [comment]
Updated.
