### ISSUE TITLE
PNG files should be renamed to png

### ISSUE THREAD

**Issue by spilinek** [thebezelproject/bezelproject-N64#4]
There's 20+ .PNG files that should have their extension changed to lower case .png

I only checked a couple of .cfg files. I noticed the .cfg files use the lower case .png. This will break things on Linux which is case sensitive.

Example: Duke Nukem 64 (USA).PNG

Duke Nukem 64 (USA).cfg
```
overlays = 1

overlay0_overlay = "Duke Nukem 64 (USA).png"

overlay0_full_screen = true

overlay0_descs = 0

````

**Comment by thebezelproject** [comment]
Corrected.
